import {
    Home,
    Package,
    Building2,
    Users,
    BookOpen,
    LifeBuoy,
    FlaskConical,
    Leaf,
    Wallet,
    Mail,
    Server,
    Zap,
    Shield,
    Code,
    Cloud,
    Briefcase,
    Smartphone,
    Globe,
    Database,
    Cpu,
    HardDrive,
    Network,
    Lock,
    FileSearch,
    ShieldCheck,
    Activity,
    BarChart,
    Settings,
  } from "lucide-react";
import type { MenuListType } from "../types/MenuList.type";
  
  export const MenuData: MenuListType[] = [
    {
      id: 1,
      name: "Home",
      icon: <Home className="w-5 h-5" />,
      subTitle: "Welcome to our comprehensive platform",
    },
    {
      id: 2,
      name: "Products & Services",
      icon: <Package className="w-5 h-5" />,
      subTitle: "Explore our comprehensive offerings",
      children: [
        {
          id: 2.1,
          name: "Software Solutions",
          icon: <Code className="w-5 h-5" />,
          subTitle: "Custom software development and deployment",
          children: [
            {
              id: 2.11,
              name: "Web Applications",
              icon: <Globe className="w-5 h-5" />,
              subTitle: "Modern web application development",
            },
            {
              id: 2.12,
              name: "Mobile Apps",
              icon: <Smartphone className="w-5 h-5" />,
              subTitle: "iOS and Android mobile solutions",
            },
            {
              id: 2.13,
              name: "Enterprise Software",
              icon: <Building2 className="w-5 h-5" />,
              subTitle: "Large-scale business applications",
            },
          ],
        },
        {
          id: 2.2,
          name: "Cloud & Infrastructure",
          icon: <Cloud className="w-5 h-5" />,
          subTitle: "Scalable cloud solutions and infrastructure",
          children: [
            {
              id: 2.21,
              name: "Cloud Migration",
              icon: <HardDrive className="w-5 h-5" />,
              subTitle: "Seamless transition to cloud platforms",
            },
            {
              id: 2.22,
              name: "Infrastructure Management",
              icon: <Network className="w-5 h-5" />,
              subTitle: "24/7 infrastructure monitoring",
            },
            {
              id: 2.23,
              name: "Database Solutions",
              icon: <Database className="w-5 h-5" />,
              subTitle: "Optimized database architecture",
            },
          ],
        },
        {
          id: 2.3,
          name: "Consulting Services",
          icon: <Briefcase className="w-5 h-5" />,
          subTitle: "Expert guidance and strategic support",
        },
      ],
    },
    {
      id: 3,
      name: "Industry Solutions",
      icon: <Building2 className="w-5 h-5" />,
      subTitle: "Specialized solutions for different industries",
      children: [
        {
          id: 3.1,
          name: "System Architecture",
          icon: <Server className="w-5 h-5" />,
          subTitle: "Scalable system design and planning",
          children: [
            {
              id: 3.11,
              name: "Microservices Design",
              icon: <Cpu className="w-5 h-5" />,
              subTitle: "Modern microservices architecture",
            },
            {
              id: 3.12,
              name: "API Development",
              icon: <Code className="w-5 h-5" />,
              subTitle: "RESTful and GraphQL APIs",
            },
            {
              id: 3.13,
              name: "System Integration",
              icon: <Network className="w-5 h-5" />,
              subTitle: "Seamless system connections",
            },
          ],
        },
        {
          id: 3.2,
          name: "Performance Optimization",
          icon: <Zap className="w-5 h-5" />,
          subTitle: "Application and system optimization",
          children: [
            {
              id: 3.21,
              name: "Load Testing",
              icon: <Activity className="w-5 h-5" />,
              subTitle: "Performance under stress testing",
            },
            {
              id: 3.22,
              name: "Code Optimization",
              icon: <Settings className="w-5 h-5" />,
              subTitle: "Efficient code refactoring",
            },
            {
              id: 3.23,
              name: "Performance Monitoring",
              icon: <BarChart className="w-5 h-5" />,
              subTitle: "Real-time performance tracking",
            },
          ],
        },
        {
          id: 3.3,
          name: "Security Audits",
          icon: <Shield className="w-5 h-5" />,
          subTitle: "Comprehensive security assessments",
          children: [
            {
              id: 3.31,
              name: "Vulnerability Assessment",
              icon: <FileSearch className="w-5 h-5" />,
              subTitle: "Identify security weaknesses",
            },
            {
              id: 3.32,
              name: "Penetration Testing",
              icon: <Lock className="w-5 h-5" />,
              subTitle: "Ethical hacking services",
            },
            {
              id: 3.33,
              name: "Compliance Audits",
              icon: <ShieldCheck className="w-5 h-5" />,
              subTitle: "Security standard compliance",
            },
          ],
        },
      ],
    },
    {
      id: 4,
      name: "Company",
      icon: <Users className="w-5 h-5" />,
      subTitle: "Learn about our organization and culture",
    },
    {
      id: 5,
      name: "Resources",
      icon: <BookOpen className="w-5 h-5" />,
      subTitle: "Knowledge base, tools, and learning materials",
    },
    {
      id: 6,
      name: "Support",
      icon: <LifeBuoy className="w-5 h-5" />,
      subTitle: "Get help and support when you need it",
    },
    {
      id: 7,
      name: "Research & Innovation",
      icon: <FlaskConical className="w-5 h-5" />,
      subTitle: "Cutting-edge research and innovation initiatives",
    },
    {
      id: 8,
      name: "Sustainability",
      icon: <Leaf className="w-5 h-5" />,
      subTitle: "Environmental responsibility and sustainable technology",
    },
    {
      id: 9,
      name: "Investor Relations",
      icon: <Wallet className="w-5 h-5" />,
      subTitle: "Financial information and investor resources",
    },
    {
      id: 10,
      name: "Contact",
      icon: <Mail className="w-5 h-5" />,
      subTitle: "Get in touch with our team",
    },
  ];
  